[package]
name = "todo-app-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "1.23", features = ["full"] }
sqlx = { version = "0.6", features = ["mysql", "runtime-tokio-native-tls", "time"] }
futures = "0.3"
chrono = "0.4"
