version: "3.9"

services:
  database:
    build: ./db
    image: todo-database-ci
    container_name: todo-database
    env_file:
      - .env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
