version: "3.9"

services:
  database:
    build: ./db
    image: todo-database-test
    container_name: todo-database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    image: todo-app-backend-test
    container_name: todo-app-backend
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@todo-database/${MYSQL_DATABASE}
    command: cargo test
