[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
dependencies = ["format"]

[tasks.down_docker]
script = "docker compose down --remove-orphans"

[tasks.down]
alias = "down_docker"

[tasks.clean_docker]
# https://qiita.com/suin/items/19d65e191b96a0079417
script = "docker compose down --rmi all --remove-orphans"
dependencies = ["down_docker"]

[tasks.clean_cargo]
command = "cargo"
args = ["clean"]

[tasks.clean]
dependencies = ["clean_cargo", "clean_docker"]

[tasks.build_docker_db]
script = "docker compose -f docker-compose.sub.yml build"

[tasks.build_docker]
script = "docker compose -f docker-compose.yml build"

[tasks.build_cargo]
env = { CARGO_INCREMENTAL = 1 }
command = "cargo"
args = ["build"]
dependencies = ["format", "lint"]

[tasks.build]
dependencies = [
    "build_docker_db",
    "build_docker",
    "build_cargo"
]

[tasks.up_db]
script = "docker compose -f docker-compose.sub.yml --env-file .env.dev up -d"

[tasks.test]
env_files = [".env.dev"]
command = "cargo"
args = ["test"]
dependencies = ["build_cargo", "up_db"]
[tasks.test.env]
DATABASE_URL = { script = ["echo mysql://root:$MYSQL_ROOT_PASSWORD@localhost:3306/$MYSQL_DATABASE"] }

[tasks.up_cargo]
env_files = [".env.dev"]
command = "cargo"
args = ["run"]
dependencies = ["test"]
[tasks.up_cargo.env]
DATABASE_URL = { script = ["echo mysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost:3306/$MYSQL_DATABASE"] }

[tasks.up]
script = "docker compose -f docker-compose.yml --env-file .env.dev up -d"

[tasks.ci]
dependencies = [
    "up_db",
    "test",
    "clean"
]

[tasks.serve_db]
command = "docker compose -f docker-compose.sub.yml --env-file .env up -d"

[tasks.serve]  # maybe
command = "docker compose -f docker-comopse.yml --env-file .env up -d"
