[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
dependencies = ["format"]

[tasks.down_docker]
script = "docker compose down --remove-orphans"

[tasks.down]
alias = "down_docker"

[tasks.clean_docker]  # https://qiita.com/suin/items/19d65e191b96a0079417
script = "docker compose down --rmi all --remove-orphans"
dependencies = ["down_docker"]

[tasks.clean_cargo]
command = "cargo"
args = ["clean"]

[tasks.clean]
dependencies = ["clean_cargo", "clean_docker"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format", "lint"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.load_env_dev]
script = "source .env.dev"

[tasks.load_env]
script = "source .env"

[tasks.up_db]
script = "docker compose -f docker-compose.sub.yml --env-file .env.dev up -d"

[tasks.up_cargo]
command = "cargo"
args = ["run"]
dependencies = ["up_db", "load_env_dev"]

[tasks.up]
script = "docker compose -f docker-compose.yml --env-file .env.dev up -d"

[tasks.serve]  # maybe
command = "docker compose -f docker-comopse.yml --env-file .env up -d"
