version: "3"

tasks:
  build:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose build
      - cargo build

  dev:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose -f docker-compose.yml --env-file .env.dev up -d

  dev-db:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose -f docker-compose.sub.yml --env-file .env.dev up -d --wait

  serve:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose -f docker-compose.yml --env-file .env up -d

  serve-db:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose -f docker-compose.sub.yml --env-file .env up -d

  ci-test:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose -f docker-compose.sub.yml --env-file .env.dev up -d --wait
      - CARGO_INCREMENTAL=1 cargo build --release --all-features
      - docker compose -f docker-compose.sub.yml --env-file .env.dev down

  down-dev:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose --env-file .env.dev down

  down:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose --env-file .env down
