DROP DATABASE IF EXISTS `todo-app-database`;
CREATE DATABASE `todo-app-database`;

USE `todo-app-database`;

CREATE TABLE `todos` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `note` VARCHAR(255) NOT NULL DEFAULT '',
    `due_to` TIMESTAMP NOT NULL,
    `done` BOOLEAN NOT NULL DEFAULT false,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL
);
