on: [push]

name: on-push-CI

jobs:
  docker_db:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout
        uses: actions/checkout@v3
      - name: setup docker-compose
        run: docker compose -f docker-compose.sub.yml --env-file .env.dev up -d
  rust_check:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout
        uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: build
        run: CARGO_INCREMENTAL=1 cargo build --release --all-features
      - name: format
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
