on: [push]

name: on-push-CI

env:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: todo-app-database

jobs:
  rust_check:
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb:10.9.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: chekcout
        uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: install rust toolchain
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: build
        run: CARGO_INCREMENTAL=1 cargo build --release --all-features
      - name: format
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: update env
        run: |
          echo "DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@localhost:3306/$MYSQL_DATABASE" >> $GITHUB_ENV
      - name: install sqlx
        uses: baptiste0928/cargo-install@v1
        with:
          crate: sqlx-cli
          version: "^0.6"
      - name: run migrate
        run: cargo sqlx migrate run --source db/migrations
      - name: run test
        run: cargo test
