name: on-push-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: todo-app-database
  CARGO_INCREMENTAL: 1
  SQLX_VERSION: "^0.6"

jobs:
  rust_check:
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb:10.9.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: chekcout
        uses: actions/checkout@v3
      - name: cache build
        uses: Swatinem/rust-cache@v2
      - name: install rust toolchain
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: install sqlx
        run: cargo install sqlx-cli@$SQLX_VERSION
      - name: build
        run: cargo build --release --all-features
      - name: format
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: update env
        run: echo "DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@localhost:3306/$MYSQL_DATABASE" >> $GITHUB_ENV
      - name: run migrate
        run: cargo sqlx migrate run --source db/migrations
      - name: run test
        run: cargo test
