on: [push]

name: on-push-CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout
        uses: actions/checkout@v2
      - name: setup docker-compose
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: compose-ci.yaml
          localhost: true
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: load env, then cargo build
        run: |
          export $(cat .env.dev | grep -v ^# | xargs)
          cargo build --release --all-features
      - name: cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
