name: on-push-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: todo-app-database
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: "target/profile/%p-%m.profraw"

jobs:
  rust_check:
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb:10.9.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: chekcout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: "nixpkgs=channel:release-23.05"
      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: cache build
        uses: Swatinem/rust-cache@v2
      - name: build
        run: nix develop -c cargo build
      - name: format
        run: nix develop -c cargo fmt --all -- --check
      - name: clippy
        run: nix develop -c cargo clippy --all-targets --all-features -- -D warnings
      - name: update env
        run: echo "DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@localhost:3306/$MYSQL_DATABASE" >> $GITHUB_ENV
      - name: run migrate
        run: nix develop -c cargo sqlx migrate run --source db/migrations
      - name: run test
        run: nix develop -c cargo test
      - name: generate LCOV
        run: nix develop -c grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/coverage.lcov
