name: on-push-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: todo-app-database
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: "target/profile/%p-%m.profraw"
  GRCOV_VERSION: 0.8.19

jobs:
  rust_check:
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb:10.9.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: chekcout
        uses: actions/checkout@v3
      - name: rust cache
        uses: Swatinem/rust-cache@v2
      - name: check fmt
        run: cargo fmt --all -- --check
      - name: check lint
        run: cargo clippy -- -D warnings
      - name: build
        run: cargo build
      - name: prepare dependnecies
        run: |
          cargo install sqlx-cli
          curl -fLO \
            "${REPO_URL}/releases/download/v${GRCOV_VERSION}/${RELEASE_TARBALL}"
          tar xf "${RELEASE_TARBALL}"
        env:
          REPO_URL: "https://github.com/mozilla/grcov"
          RELEASE_TARBALL: "grcov-x86_64-unknown-linux-musl.tar.bz2"
      - name: update env
        run: echo "DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@localhost:3306/$MYSQL_DATABASE" >> $GITHUB_ENV
      - name: run migrate
        run: cargo sqlx migrate run --source db/migrations
      - name: run test
        run: cargo test
      - name: generate LCOV
        run: ./grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/coverage.lcov
